### ISSUE TITLE
Support netstandard2.1

### ISSUE THREAD

**Issue by warappa** [BionicFramework/BionicMonitor#7]
Currently BionicMonitor only checks for Blazor files if the **target framework is `netstandard2.0`**.
Since **Blazor Preview 7** I needed to upgrade to **`netstandard2.1`**. Unfortunately, BionicMonitor only checks for the _netstandard2.0_ folder on the following line:
https://github.com/BionicFramework/BionicMonitor/blob/91a41d2b0aa8d29f096bb8a279546742163226c5/BionicMonitorService/BionicMonitorService.cs#L41

Maybe BionicMonitor could 

- check for both/new target framework(s) or
- provide a command-line option for that

### Workaround
I made a symbolic link from my `bin\Debug\netstandard2.1` folder to `bin\Debug\netstandard2.0`.
`mklink netstandard2.0 netstandard2.1` (on Windows)

Otherwise:
Thank you for this valuable tool!

**Comment by NostraDavid** [comment]
netstandard3.0 has the same problem :(
No hot-reloading for me.

**Comment by bmsantos** [comment]
@warappa  and @NostraDavid, thanks for reporting it.

The issue is that when using dotnet 3.1.100 preview, Blazor Web Client app will not work when using netstandard2.1. So I guess you guys are using this for other things other than Blazor development.

I'll have a look on this issue soon.

**Comment by bmsantos** [comment]
Bionic Monitor 1.0.21 was just released and fixes this issue.
Please update Bionic Monitor by executing:

```bash
biomon update
```

Let me know if you find any other issue.
